import DipoleCalculator from '../../../_components/calculators/DipoleCalculator';
import CalculatorPageTemplate from '../../../_components/layouts/CalculatorPageTemplate';
import { SEOSection, SEOList, SEOFAQ, SEOFormula } from '../../../_components/ui/SEOContent';
import { createInternalLink } from '../../../_components/ui/SEOInternalLink';

export default function DipoleCalculatorPage() {
  return (
    <CalculatorPageTemplate
      title="Dipole Calculator - Calculate Electric Dipole Moment Instantly"
      description="Calculate electric dipole moment from charge and distance. Free physics calculator with instant results for electrostatics and molecular analysis."
      calculator={<DipoleCalculator />}
      slug="physics/dipole-calculator"
      category="Physics"
      features={[
        "Instant dipole moment calculations",
        "Support for Debye and Coulomb-meter units",
        "Calculate dipole moment, charge, or distance",
        "Step-by-step calculation breakdown",
        "Free to use"
      ]}
    >
      <SEOSection title="Why Dipole Moment Calculations Matter">
        <p>
          From understanding why water is such an excellent solvent to designing advanced electronic materials, the electric dipole moment is a crucial concept. It measures how electrical charge separates in molecules and materials, determining their chemical behavior and physical properties. Whether you're analyzing molecular polarity, designing materials, or solving physics problems, our dipole calculator instantly computes dipole moments, charges, or distances using the fundamental relationship p = q × d. For related electromagnetic calculations, explore our {createInternalLink('electric-field-calculator')} to analyze forces generated by these dipoles.
        </p>
      </SEOSection>

      <SEOSection title="How to Use This Calculator">
        <p>Follow these steps to get instant results:</p>
        <ol>
          <li><strong>Step 1:</strong> Enter the charge magnitude in Coulombs or elementary charge units.</li>
          <li><strong>Step 2:</strong> Input the distance between charges in meters, Angstroms, or other distance units.</li>
          <li><strong>Step 3:</strong> Click Calculate to instantly see the dipole moment in Debye or Coulomb-meters with complete breakdown.</li>
        </ol>
      </SEOSection>

      <SEOSection title="The Core Concept: Dipole Calculator Formula">
        <p>
          An electric dipole moment measures the separation of positive and negative charges. It depends on both the charge magnitude and the distance between charges. Larger charges or greater separation both increase the dipole moment, indicating stronger electrical polarity in the system.
        </p>
        <div className="bg-gray-100 p-4 rounded-lg text-center my-4">
          <p className="font-mono text-lg font-bold">p = q × d</p>
        </div>
        <p className="text-sm text-gray-600 mb-4">
          Where: p = dipole moment (C·m or Debye), q = charge magnitude (C), d = distance between charges (m)
        </p>
        <h4 className="font-semibold mt-4">Worked Example:</h4>
        <p>Calculate the dipole moment for a charge separation of 1.5 Ångströms with charge magnitude of 1 elementary charge (e = 1.602 × 10⁻¹⁹ C):</p>
        <ul>
          <li>Charge: 1.602 × 10⁻¹⁹ C (elementary charge)</li>
          <li>Distance: 1.5 Å = 1.5 × 10⁻¹⁰ m</li>
          <li>Calculation: p = (1.602 × 10⁻¹⁹ C) × (1.5 × 10⁻¹⁰ m) = 2.403 × 10⁻²⁹ C·m</li>
          <li>Result: p ≈ 0.72 Debye (typical molecular dipole)</li>
        </ul>
      </SEOSection>

      <SEOSection title="Practical Applications">
        <p>Dipole moment calculations are essential across numerous industries and applications:</p>
        <SEOList items={[
          "Molecular Chemistry: Determining molecular polarity, predicting solubility, and understanding intermolecular forces in chemical compounds",
          "Materials Science: Characterizing dielectric and ferroelectric materials, designing semiconductors and electronic devices",
          "Pharmacology: Predicting drug-receptor interactions, analyzing molecular properties for bioavailability and efficacy",
          "Spectroscopy: Interpreting infrared and microwave spectra to determine molecular structure and vibrational modes",
          "Physics Education: Teaching electrostatics concepts, molecular structure, and electromagnetic interactions in academic settings"
        ]} />
      </SEOSection>

      <SEOSection title="Frequently Asked Questions (FAQ)">
        <SEOFAQ questions={[
          {
            question: "What is an electric dipole moment?",
            answer: "An electric dipole moment measures the separation of positive and negative charges in a system. It's calculated as p = q × d, where q is the magnitude of the charge and d is the distance between charges. A larger dipole moment indicates a more polar system. The dipole moment is a vector pointing from negative to positive charge."
          },
          {
            question: "What is the formula for calculating dipole moment?",
            answer: "The dipole moment magnitude is: p = q × d, where p is the dipole moment, q is the charge magnitude, and d is the distance between charges. You can rearrange this to find charge (q = p/d) or distance (d = p/q) if the other values are known."
          },
          {
            question: "What are the units of dipole moment?",
            answer: "The SI unit is Coulomb-meter (C·m). However, the Debye (D) is commonly used for molecular dipoles, where 1 D = 3.33564 × 10⁻³⁰ C·m. Our calculator supports both units for easy conversion."
          },
          {
            question: "How does dipole moment relate to molecular polarity?",
            answer: "A non-zero dipole moment indicates a polar molecule, while a zero dipole moment (symmetric charge distribution) indicates a nonpolar molecule. Larger dipole moments mean more polar molecules. For example, water (1.85 D) is highly polar, while CO₂ (0 D) is nonpolar."
          },
          {
            question: "Can a neutral system have a dipole moment?",
            answer: "Yes! A system with zero net charge can have a non-zero dipole moment due to charge separation. Water is a perfect example: it has zero net charge but a dipole moment of 1.85 D because electrons are unevenly distributed around the molecule's oxygen atom."
          }
        ]} />
      </SEOSection>

      <SEOSection title="Conclusion">
        <p>
          Mastering dipole moment calculations is essential for understanding molecular behavior and designing materials. Our calculator provides instant, accurate results for analyzing charge separation and electrical polarity.
        </p>
        <p>
          Explore more Physics tools: Check out our {createInternalLink('charge-calculator')} for electrical charge analysis or discover the {createInternalLink('electrostatic-force-calculator')} for force calculations between charges.
        </p>
      </SEOSection>
    </CalculatorPageTemplate>
  );
}

